//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaloriTakip.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KaloriTakipEntities2 : DbContext
    {
        public KaloriTakipEntities2()
            : base("name=KaloriTakipEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_AksamYemegi> tbl_AksamYemegi { get; set; }
        public virtual DbSet<tbl_AraOgun> tbl_AraOgun { get; set; }
        public virtual DbSet<tbl_Bildirimler> tbl_Bildirimler { get; set; }
        public virtual DbSet<tbl_Diyetisyen> tbl_Diyetisyen { get; set; }
        public virtual DbSet<tbl_DiyetisyenlerinHastalari> tbl_DiyetisyenlerinHastalari { get; set; }
        public virtual DbSet<tbl_Kahvaltı> tbl_Kahvaltı { get; set; }
        public virtual DbSet<tbl_KiloTakip> tbl_KiloTakip { get; set; }
        public virtual DbSet<tbl_Kullanici> tbl_Kullanici { get; set; }
        public virtual DbSet<tbl_OgleYemegi> tbl_OgleYemegi { get; set; }
        public virtual DbSet<tbl_Yemek> tbl_Yemek { get; set; }
        public virtual DbSet<tbl_Yetki> tbl_Yetki { get; set; }
        public virtual DbSet<tbl_Yonetici> tbl_Yonetici { get; set; }
        public virtual DbSet<ilceler> ilceler { get; set; }
        public virtual DbSet<iller> iller { get; set; }
    }
}
