//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaloriTakip.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Kullanici()
        {
            this.tbl_AksamYemegi = new HashSet<tbl_AksamYemegi>();
            this.tbl_AraOgun = new HashSet<tbl_AraOgun>();
            this.tbl_Bildirimler = new HashSet<tbl_Bildirimler>();
            this.tbl_DiyetisyenlerinHastalari = new HashSet<tbl_DiyetisyenlerinHastalari>();
            this.tbl_Kahvaltı = new HashSet<tbl_Kahvaltı>();
            this.tbl_KiloTakip = new HashSet<tbl_KiloTakip>();
            this.tbl_OgleYemegi = new HashSet<tbl_OgleYemegi>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "Name can't be empty")]
        public string Adi { get; set; }
        [Required(ErrorMessage = "Surname can't be empty")]
        public string Soyadi { get; set; }
        [Required(ErrorMessage = "Email can't be empty")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail is not valid")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Password can't be empty")]
        public string Sifre { get; set; }
        [Required(ErrorMessage = "Gender can't be empty")]
        public string Cinsiyet { get; set; }
        public Nullable<int> Yetki { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AksamYemegi> tbl_AksamYemegi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AraOgun> tbl_AraOgun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Bildirimler> tbl_Bildirimler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DiyetisyenlerinHastalari> tbl_DiyetisyenlerinHastalari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Kahvaltı> tbl_Kahvaltı { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KiloTakip> tbl_KiloTakip { get; set; }
        public virtual tbl_Yetki tbl_Yetki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OgleYemegi> tbl_OgleYemegi { get; set; }
    }
}
