//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaloriTakip.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Yonetici
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Name can't be empty")]
        public string Adi { get; set; }

        [Required(ErrorMessage = "Surname can't be empty")]
        public string Soyadi { get; set; }

        [Required(ErrorMessage = "Email can't be empty")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail is not valid")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Password can't be empty")]
        public string Sifre { get; set; }
        public Nullable<int> Yetki { get; set; }
    }
}
