//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaloriTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DiyetisyenlerinHastalari
    {
        public int ID { get; set; }
        public Nullable<int> Diyetisyen { get; set; }
        public Nullable<int> Kullanici { get; set; }
    
        public virtual tbl_Diyetisyen tbl_Diyetisyen { get; set; }
        public virtual tbl_Kullanici tbl_Kullanici { get; set; }
    }
}
