//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaloriTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Yemek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Yemek()
        {
            this.tbl_AksamYemegi = new HashSet<tbl_AksamYemegi>();
            this.tbl_AraOgun = new HashSet<tbl_AraOgun>();
            this.tbl_Kahvaltı = new HashSet<tbl_Kahvaltı>();
            this.tbl_OgleYemegi = new HashSet<tbl_OgleYemegi>();
        }
    
        public int ID { get; set; }
        public string YemekAdi { get; set; }
        public Nullable<double> Kalori_100Gram_ { get; set; }
        public Nullable<double> ProteinMiktari { get; set; }
        public Nullable<double> KarbonhidratMiktari { get; set; }
        public Nullable<double> YagMiktari { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AksamYemegi> tbl_AksamYemegi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AraOgun> tbl_AraOgun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Kahvaltı> tbl_Kahvaltı { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OgleYemegi> tbl_OgleYemegi { get; set; }
    }
}
