//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaloriTakip.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_KiloTakip
    {
        public int ID { get; set; }
        public Nullable<int> Kullanici { get; set; }

        [Required(ErrorMessage = "Weight can't be empty")]
        [Range(40, 250, ErrorMessage = "Weight is not valid.")]
        public Nullable<double> MevcutKilosu { get; set; }

        [Required(ErrorMessage = "Height can't be empty")]
        [Range(100, 250, ErrorMessage = "Height is not valid.")]
        public Nullable<int> MevcutBoy { get; set; }
        public Nullable<int> GunlukKalori { get; set; }

        [Required(ErrorMessage = "Age can't be empty")]
        [Range(14, 90, ErrorMessage = "Age is not valid.")]
        public Nullable<int> Yas { get; set; }

        [Required(ErrorMessage = "Physical activity level can't be empty")]
        public string AktiviteSeviyesi { get; set; }
    
        public virtual tbl_Kullanici tbl_Kullanici { get; set; }
    }
}
